# Generated by Django 4.2.7 on 2024-02-04 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', related_query_name='mail', to=settings.AUTH_USER_MODEL, verbose_name='автор рассылки'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='recipient',
            field=models.ManyToManyField(related_name='clients', to='clients.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingmessage', verbose_name='рассылка'),
        ),
    ]
