# Generated by Django 4.2.7 on 2024-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='контактный email')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент рассылки',
                'verbose_name_plural': 'клиенты рассылки',
                'ordering': ('email',),
            },
        ),
    ]
